### ISSUE TITLE
[ Feature Request ] Usage without email

### ISSUE THREAD

**Issue by c33s** [markt-de/puppet-acme#36]
letsencrypt/certbot allows the usage without email address but this puppetmodule has a hard requirement to accounts/email adresses. would be awesome to allow the usage of this module without providing a email address.

**Comment by fraenki** [comment]
Well, you could submit a PR if you don't want to specify an e-mail address :)

**Comment by fraenki** [comment]
2 years have passed and there was not enough interest to implement this, so let's close this issue.
If there's still someone interested in this, please submit a PR.
