### ISSUE TITLE
[ Bug / Suggestion ] default_ca should also be used for acme::certificate

### ISSUE THREAD

**Issue by c33s** [markt-de/puppet-acme#37]
`acme::certificate` requires the definition of the ca but should also use the default ca if not provided

**Comment by fraenki** [comment]
What would be the benefit, could you provide a example config to demonstrate how this would be an improvement?

**Comment by c33s** [comment]
i just used `acme::certificate` and wondered why it fails as i had not defined the `ca`.  i would assume that if i have defined a `default_ca` everywhere where i can provide a `ca` that it is optional and if it is not provided the default is taken

related to #38. i provided a usecase in my comment there https://github.com/fraenki/puppet-acme/issues/38#issuecomment-1009952253

**Comment by fraenki** [comment]
Implemented in https://github.com/markt-de/puppet-acme/commit/90cef4e88583ed305044cbeecb3f11d8f5ae6967.
