### ISSUE TITLE
[ Feature Request ] default_account and default_profile

### ISSUE THREAD

**Issue by c33s** [markt-de/puppet-acme#38]
would be handy to be able to define a default account

**Comment by fraenki** [comment]
How and where? Could you elaborate more on this?

**Comment by c33s** [comment]
it just would be simpler to use the `acme::certificate` as you would not be required to add all the parameters again.

for example:
`host.yaml` (hiera)
```
acme::default_profile: my_profile
acme::default_account: certmaster@example.com
acme::default_ca: letsencrypt_test
```

`webserver.pp`:
```
...
include acme

acme::certificate { 'example.com'; }

#instead of

acme::certificate { 'example.com':
  use_profile => 'my_profile',
  use_account => 'certmaster@example.com',
  ca          => 'letsencrypt_test',
}
...
```

hope i described better what i mean. just let me know if you need more detail

**Comment by fraenki** [comment]
Implemented in https://github.com/markt-de/puppet-acme/commit/2dbbddef40d4a9790b94e149273eebe32c9331cb. Currently untested... :)
