### ISSUE TITLE
secret leakage - Puppetboard

### ISSUE THREAD

**Issue by DennisPohlmann** [markt-de/puppet-acme#49]
Hey,

we use Puppetboard for our environments. We have some secrets leakage here:
![bug](https://github.com/markt-de/puppet-acme/assets/50769263/db7d054f-a375-4823-a4cb-ba2ee49d48a1)
![bug2](https://github.com/markt-de/puppet-acme/assets/50769263/4c599182-bc8b-465b-8f3c-8ad935bcde19)

Can we remove this notice?: https://github.com/markt-de/puppet-acme/blob/13b1f41288338ab27004578164f36e6c30c56f0a/manifests/request.pp#L132

**Comment by DennisPohlmann** [comment]
Also https://github.com/markt-de/puppet-acme/blob/13b1f41288338ab27004578164f36e6c30c56f0a/manifests/request.pp#L214 should be removed. Or can this be disabled somehow?

**Comment by fraenki** [comment]
Sure, no objections, let's remove it. Would you submit a PR?
It was only ever meant as a status message for debug purposes.

**Comment by DennisPohlmann** [comment]
@fraenki Thanks for the update. Will create a PR, otherwise it works like a charm. Thanks for your work.
